typography_spectrum: 0.75761
content_rating:
  adult: false
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.18701289989985526
  lightness: 0.8688199163880199
  saturation: 0.6043563140556216
  rhythmicContrast: 0.7571154900360852
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5429864614270627
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3ed6e3b3-3b41-4f7c-8eb3-ecc41dfcd4ff.jpg
name: ENERMEC
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
